/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './client/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#006e6e",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c4c6cf",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#aec7f7",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#d6e3ff",
        "primary": "#002046",
        "on-secondary-fixed-variant": "#004f4f",
        "tertiary-fixed-dim": "#f1bd81",
        "on-tertiary-fixed": "#2b1700",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        "background": "#f7f9fb",
        "tertiary-container": "#4f2f00",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "on-secondary-fixed": "#002020",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#c6965e",
        "on-surface-variant": "#44474e",
        "tertiary-fixed": "#ffddb9",
        "surface-dim": "#d8dadc",
        "on-primary": "#ffffff",
        "on-primary-container": "#87a0cd",
        "secondary-fixed-dim": "#76d6d5",
        "tertiary": "#321c00",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "surface-tint": "#465f88",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "secondary": "#006a6a",
        "primary-container": "#1b365d",
        "on-primary-fixed": "#001b3d",
        "secondary-container": "#90efef",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#623f0f",
        "on-primary-fixed-variant": "#2e476f",
        "primary-fixed-dim": "#aec7f7",
        "on-surface": "#191c1e",
        "outline": "#74777f",
        "on-secondary": "#ffffff",
        "surface": "#f7f9fb",
        "secondary-fixed": "#93f2f2",
        "accent": "#F5A623",
        "accent-hover": "#D98E18"
      },
    },
  },
  plugins: [],
};
