import React, { useEffect, useState } from 'react';
import api from '../../services/api';
import { useAuth } from '../../context/AuthContext';

export default function Recommendations() {
  const { user } = useAuth();
  const [recommendations, setRecommendations] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [currentAssignment, setCurrentAssignment] = useState('');

  useEffect(() => {
    const fetchRecommendations = async () => {
      if (!user || (!user.id && !user._id)) {
        setIsLoading(false);
        return;
      }
      const userId = user.id || user._id;
      setIsLoading(true);

      try {
        const res = await api.get(`/api/courses/recommendations/${userId}`);
        if (res.data && res.data.success && Array.isArray(res.data.recommendations)) {
          setRecommendations(res.data.recommendations);
          setCurrentAssignment(res.data.currentAssignment || 'None');
        }
      } catch (err) {
        console.error('Failed to load API recommendations:', err);
      } finally {
        setIsLoading(false);
      }
    };

    fetchRecommendations();
  }, [user]);

  return (
    <div className="flex-1 bg-surface min-h-screen p-4 md:p-8 max-w-[1280px] mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-outline-variant pb-6">
        <div>
          <h2 className="text-2xl md:text-3xl font-bold text-primary flex items-center gap-2">
            <span className="material-symbols-outlined text-secondary text-3xl">auto_awesome</span>
            Recommended Learning Paths
          </h2>
          <p className="text-xs md:text-sm text-on-surface-variant mt-1">
            Personalized course recommendations generated by analyzing your skill gaps and active project assignment.
          </p>
        </div>

        {currentAssignment && currentAssignment !== 'None' && (
          <div className="bg-teal-50 border border-teal-200 text-teal-900 px-4 py-2 rounded-xl text-xs flex items-center gap-2 shadow-xs">
            <span className="material-symbols-outlined text-secondary text-base">work</span>
            <div>
              <span className="font-semibold block text-[10px] text-teal-700 uppercase tracking-wider">Active Assignment</span>
              <span className="font-bold text-teal-950">{currentAssignment}</span>
            </div>
          </div>
        )}
      </div>

      {/* Recommendations Cards Grid */}
      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {[1, 2, 3, 4].map((n) => (
            <div key={n} className="bg-surface-container-lowest border border-outline-variant rounded-xl p-6 animate-pulse h-64" />
          ))}
        </div>
      ) : recommendations.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {recommendations.map((course) => (
            <article
              key={course._id || course.courseCode}
              className="bg-surface-container-lowest border border-outline-variant rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between space-y-5"
            >
              {/* Top Badge & Domain Header */}
              <div>
                <div className="flex justify-between items-start gap-2 mb-3">
                  <span className="text-[11px] font-bold uppercase tracking-wide bg-surface-container-high text-primary px-3 py-1 rounded-md">
                    {course.domain || 'Statistical'}
                  </span>
                  <div className="flex items-center gap-2">
                    {course.isAssignmentMatch && (
                      <span className="text-[11px] font-bold text-teal-800 bg-teal-50 border border-teal-200 px-2.5 py-0.5 rounded-full flex items-center gap-1">
                        <span className="material-symbols-outlined text-xs">work</span> Project Boost
                      </span>
                    )}
                    <span className="text-[11px] font-bold text-primary bg-primary-container/10 px-2.5 py-0.5 rounded-full border border-primary/20">
                      {course.recommendationScore || 80}% Match
                    </span>
                  </div>
                </div>

                {/* Course Title & Provider */}
                <h3 className="text-lg font-bold text-on-surface leading-snug mb-1">
                  {course.title}
                </h3>
                <p className="text-xs text-on-surface-variant font-mono mb-4">
                  {course.courseCode} • {course.provider} • {course.duration || '5 days'}
                </p>

                {/* Skill Tags */}
                <div className="flex flex-wrap gap-1.5 mb-4">
                  {course.skillTags?.map((tag) => (
                    <span
                      key={tag}
                      className="text-xs font-semibold bg-slate-100 text-slate-700 px-2.5 py-1 rounded-md"
                    >
                      {tag}
                    </span>
                  ))}
                </div>

                {/* AI INSIGHT CALLOUT BOX */}
                <div className="bg-gradient-to-r from-teal-50/90 to-blue-50/90 border border-teal-200/80 rounded-lg p-3 flex items-start gap-2.5 shadow-2xs">
                  <span className="material-symbols-outlined text-secondary text-lg flex-shrink-0 mt-0.5">
                    auto_awesome
                  </span>
                  <div className="text-xs leading-relaxed text-slate-800">
                    <span className="font-bold text-primary mr-1">AI Recommendation Insight:</span>
                    <span>
                      {course.reason ||
                        `Recommended because of a ${course.gapSeverity || 'HIGH'} gap in ${course.matchedSkills?.[0] || 'core skill'}.`}
                    </span>
                  </div>
                </div>
              </div>

              {/* Bottom Actions */}
              <div className="pt-4 border-t border-outline-variant/60 flex items-center justify-between">
                <span className="text-xs font-semibold text-on-surface-variant">
                  Level {course.level || 3} Certification
                </span>
                <a
                  href="#igot-portal"
                  className="bg-[#F5A623] hover:bg-[#D98E18] text-white font-extrabold text-xs px-5 py-2.5 rounded-xl transition-colors flex items-center justify-center gap-1.5 shadow-md cursor-pointer"
                >
                  <span>Start Learning</span>
                  <span className="material-symbols-outlined text-sm">arrow_forward</span>
                </a>
              </div>
            </article>
          ))}
        </div>
      ) : (
        <div className="p-12 text-center bg-surface-container-lowest border border-outline-variant rounded-xl text-sm text-on-surface-variant">
          No recommendations available at this time.
        </div>
      )}
    </div>
  );
}
